- example/README.md
The rojo project is located at /example.project.json, not
/example.default.json.
> Fix rojo build command

- docs/Installation.md
The link originally pointed to the wrong location (https://github.com/UpliftGames/moonwave/releases/latest) when it seemingly meant to point to the latest release of this repo.
> Fix latest release link

- docs/GettingStarted.md
In Getting Started, we use the title `components.lua`, but then require it in `system/poisonHurts.lua` as `script.Parent.Components`.
Components should've been lowercase.
> Fix mismatching components.lua name in GettingStarted

- lib/Loop.lua
Before this change, stacktraces of errors in systems would be truncated.
```lua
local function third(argument)
argument += 1
end
local function second()
third({})
end
local function first()
second()
end
local function system(world)
first()
end
return system
```
```
ServerScriptService.Game.systems.system->system: ServerScriptService.Game.systems.system:2: attempt to perform arithmetic (add) on table and number  -  Server
12:49:43.023  Stack Begin  -  Studio
12:49:43.023  Stack End  -  Studio
12:49:43.023  Matter: The above error will be suppressed for the next 10 seconds  - 
```
This expands them.
```
ServerScriptService.Game.systems.system->system: ServerScriptService.Game.systems.system:2: attempt to perform arithmetic (add) on table and number
ServerScriptService.Game.systems.system:2 …
```
> Correct system error stacktraces

- lib/World.lua
- lib/World.spec.lua
Example:
in runtime.server.ts after starting the loop:
```ts
task.spawn(() => {
task.wait(1);
for (let i = 0; i < 10; i++) {
world.spawn(TestComponent({ value: 0 }));
}
});
```
TestSystem1:
```ts
export = (world: World) => {
// check for newly added Test Components -- does print "ADDED"
for (const [entity, testComponentRecord] of world.queryChanged(TestComponent)) {
if (!testComponentRecord.old) {
print("ADDED");
}
}
// increment all TestComponents by one -- this change modifies the TestComponentRecord for the TestSystem2
const TestComponents: [Entity<[TestComponent]>, TestComponent][] = [];
for (const [entity, testComponent] of world.query(TestComponent)) {
TestComponents.push([entity, testComponent]);
}
for (const [entity, testComponent] of TestComponents) {
world.insert(entity, …
```
> Store Entire Change Between queryChanged Calls

- lib/World.lua
The comments associated with `_archetypes` and `_entityArchetypes` are improperly assigned and, as such, flipped. The appropriate comments are swapped between the two. This PR just changes that to better reflect how these tables are used internally.
> Fix comments on structure of `_archetypes` and `_entityArchetypes`

- lib/debugger/debugger.lua
Ran into this issue attempt to use the debugger. Perhaps there's a better way to announce this warning. Having something like this would have saved me a bit of time and is probably a good start.
> Add caution tip for autoInitialize docs

- docs/Guides/MatterDebugger.md
Ran into this issue following the docs. Bumping the version of Plasma to match the one in the example project.
> Suggest compatible Plasma in debugger docs

- docs/GettingStarted.md
The current link points to an invalid page (/example/server). It should just be /example/.
> Fix example link.

- docs/BestPractices/Reconciliation.md
The previous page was still using a older version of queryChanged where you could pass multiple components.
> Update Reconciliation Page for the new QueryChanged API

- CHANGELOG.md
- lib/init.lua
This PR ensures that the exported Matter object is read-only, which prevents invalid mutations to it
> Ensure exported matter object is read only

- CHANGELOG.md
- lib/hooks/log.lua
`Matter.log` for some reason returns `state.deltaTime` (which is not specified at all and is redundant anyways) - this PR gets rid of the redundant return value.
> Change `Matter.log` to return nothing as expected

- CHANGELOG.md
- lib/hooks/useEvent.lua
Correct parameter types and make them clear, as well as minor documentation improvements and corrections.
> Improve docs for `Matter.useEvent`

- aftman.toml
It's my first time using Matter and I was attempting to serve the `example.project.json` and then sync with it during my Studio instance. There was an attribute issue that was disabling me from syncing with the Rojo connection.
The error is as follows:
I noticed that the Rojo version within `aftman.toml` was outdated, so I updated it in this fork. I can confirm that this fixed my issue with the error and can now sync as expected. Anybody who's new to using Matter shouldn't run into this issue any longer.
Thanks.
> Update Rojo's version to 7.2.1 to mitigate attribute error

- example/src/server/systems/mothershipsSpawnRoombas.lua
- example/src/server/systems/roombasMove.lua
- example/src/server/systems/spawnMotherships.lua
- example/src/server/systems/spawnRoombas.lua
Get rid of unused variables in some files in the example game codebase to clear up Luau LSP warnings.
> Cleanup example game's codebase

- CHANGELOG.md
- lib/component.lua
- lib/component.spec.lua
> Improve error message when a component instance is accidentally passed instead of a component

- lib/debugger/debugger.lua
Matter debugger can sometimes collide with ingame HUD elements (blanked out in this screenshot for proprietary reasons)
This PR changes the DisplayOrder of the matter debugger to appear above any in-game HUD elements.
> Debugger Appears Above Ingame UI

- CHANGELOG.md
- lib/Loop.lua
- lib/Loop.spec.lua
> Improve system scheduler logic

- lib/debugger/widgets/worldInspect.lua
When inspecting Worlds with large amount of unique components, it can take some time to drill into the component you are looking to inspect further. Usually there is a specific component name in mind. Sorting the list by component name would improve my workflow a ton.
Before this change, the order of components was non-deterministic and would sometimes jump around when new components were added/removed. Now the list will remain static.
Before:
After:
> Sort component list in World Inspector

- lib/debugger/ui.lua
Addresses #51
Outcome:
Clicking on a states entry twice will close it again. This behavior is consistent with clicking on a system entry below.
https://github.com/evaera/matter/assets/5725602/89d64513-7643-4151-bff3-3ebe4dd629c1
> Allow debugger states views to be toggled like systems

- example/src/server/systems/updateTransforms.lua
The use of `return` instead of `continue` results in only one model being despawned per system run.
> Replaced return statement with continue

- lib/debugger/ui.lua
We reset the Plasma key to nil to prevent the widget from re-rendering
Fixes #72
> Fix system widgets not appearing sometimes

- lib/debugger/hookWidgets.lua
`dummyHandles` can now optionally return a function so that it can support reading from widget arguments
Fixes #66
> Support functions in dummyHandles to support widget configs

- lib/debugger/hookWidgets.lua
Fixes the issue where it errors when you are only passing a number to debug widgets' slider. With this change, it will now check whether config is a table before indexing into initial.
> Add check for config

- .gitignore
- example.project.json
Building game currently doesn't work, as it tries to put packages which are now dev-dependencies as the root of the Matter lib.
This is a regression from #89 
Right now the most straightforward fix is just keeping "Lib" as a folder with Matter. However we could also just remove Lib as a folder and have Matter directly under ReplicatedStorage, however that would require us to change every path that depends on Matter/*.
> Example packages regression fix
